server:
  port: 1114

spring:
  application:
    name: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/   #此处改为包含两个eureka-server
#,http://localhost:1112/eureka/   此处改为包含两个eureka-server